title: Design your own image for the SenseHAT
hero_image: images/banner.png
description: Design and draw your own image for the SenseHAT
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Design your own image for the SenseHAT
